"""一次性脚本：从彩虹社成员表生成 backend/app/data/terms/vtuber.json"""
import json
from pathlib import Path

# (日文主名, 中文译名, 罗马字, 备注)
MEMBERS = [
    ("月ノ美兎", "月之美兔", "Tsukino Mito", ""),
    ("勇気ちひろ", "勇气千寻", "Yuuki Chihiro", "已毕业"),
    ("える", "艾露", "Elu", ""),
    ("樋口楓", "樋口枫", "Higuchi Kaede", ""),
    ("静凛", "静凛", "Shizuka Rin", ""),
    ("渋谷ハジメ", "涩谷初", "Shibuya Hajime", ""),
    ("鈴谷アキ", "铃谷秋", "Suzuya Aki", "已毕业"),
    ("モイラ", "摩伊拉", "Moira", ""),
    ("鈴鹿詩子", "铃鹿诗子", "Suzuka Utako", "已毕业"),
    ("宇志海いちご", "宇志海莓", "Ushimi Ichigo", ""),
    ("家長むぎ", "家长麦", "Ienaga Mugi", ""),
    ("夕陽リリ", "夕阳莉莉", "Yuhi Riri", ""),
    ("物述有栖", "物述有栖", "Mononobe Alice", ""),
    ("文野環", "文野环", "Fumino Tamaki", ""),
    ("伏見ガク", "伏见学", "Fushimi Gaku", ""),
    ("ギルザレンIII世", "吉尔扎伦三世", "Gilzaren III", ""),
    ("剣持刀也", "剑持刀也", "Kenmochi Toya", ""),
    ("森中花咲", "森中花咲", "Morinaka Kazaki", ""),
    ("叶", "叶", "Kanae", "常写作「叶」，中文圈译名「叶」"),
    ("赤羽葉子", "赤羽叶子", "Akaba Youko", ""),
    ("笹木咲", "笹木咲", "Sasaki Saku", ""),
    ("闇夜乃モルル", "暗夜乃莫露露", "Yamiyono Moruru", "已毕业"),
    ("本間ひまわり", "本间向日葵", "Honma Himawari", ""),
    ("魔界ノりりむ", "魔界之莉莉姆", "Makaino Ririmu", ""),
    ("葛葉", "葛叶", "Kuzuha", ""),
    ("雪汝", "雪汝", "Setsuna", "已毕业"),
    ("椎名唯華", "椎名唯华", "Shiina Yuika", ""),
    ("ドーラ", "多拉", "Dola", ""),
    ("海夜叉神", "海夜叉神", "Marine Yaksa", "已毕业"),
    ("名伽尾アズマ", "名伽尾吾妻", "Nakao Azuma", "已毕业"),
    ("出雲霞", "出云霞", "Izumo Kasumi", "已毕业"),
    ("轟京子", "轰京子", "Todoroki Kyoko", ""),
    ("シスター・クレア", "修女·克蕾雅", "Sister Cleaire", ""),
    ("花畑チャイカ", "花畑嘉依卡", "Hanabatake Chaika", ""),
    ("鈴木勝", "铃木胜", "Suzuki Masaru", ""),
    ("安土桃", "安土桃", "Momo Azuchi", "已毕业"),
    ("卯月コウ", "卯月光", "Uzuki Kou", ""),
    ("緑仙", "绿仙", "Ryuu Shen", ""),
    ("八朔ゆず", "八朔柚子", "Hassaku Yuzu", "已毕业"),
    ("社築", "社筑", "Yashiro Kizuku", ""),
    ("神田笑一", "神田笑一", "Kanda Shoichi", ""),
    ("鳴門こがね", "鸣门小金", "Naruto Kogane", "已毕业"),
    ("飛鳥ひな", "飞鸟雏", "Asuka Hina", ""),
    ("春崎エアル", "春崎艾尔", "Harusaki Air", ""),
    ("雨森小夜", "雨森小夜", "Amemori Sayo", ""),
    ("鷹宮リオン", "鹰宫莉音", "Takamiya Rion", ""),
    ("舞元啓介", "舞元启介", "Maimoto Keisuke", ""),
    ("竜胆尊", "龙胆尊", "Rindou Mikoto", ""),
    ("でびでび・でびる", "德比德比·德比鲁", "Debidebi Debiru", ""),
    ("桜凛月", "樱凛月", "Sakura Ritsuki", ""),
    ("町田ちま", "町田千麻", "Machita Chima", ""),
    ("月見しずく", "月见雫", "Tsukimi Shizuku", "已毕业"),
    ("ジョー・力一", "周·力一", "Joe Rikiichi", ""),
    ("遠北千南", "远北千南", "Achikita Chinami", "已毕业"),
    ("成瀬鳴", "成濑鸣", "Naruse Naru", "已毕业"),
    ("ベルモンド・バンデラス", "贝尔蒙德·班德拉斯", "Belmond Banderas", ""),
    ("矢車りね", "矢车理音", "Yaguruma Rine", ""),
    ("夢追翔", "梦追翔", "Yumeoi Kakeru", ""),
    ("黒井しば", "黑井柴", "Kuroi Shiba", ""),
    ("黒羽黒兎", "黑羽黑兔", "Kuroto Kurohane", "已退出"),
    ("神成ポアロ", "神成Poirot", "Kaminari Poaro", "已退出"),
    ("童田明治", "童田明治", "Warabeda Meiji", "已毕业"),
    ("久遠千歳", "久远千岁", "Kudou Chitose", "已毕业"),
    ("郡道美玲", "郡道美玲", "Gundo Mirei", "已毕业"),
    ("夢月ロア", "梦月萝娅", "Yuzuki Roa", ""),
    ("小野町春香", "小野町春香", "Onomachi Haruka", "已毕业"),
    ("語部紡", "语部纺", "Kataribe Tsumugu", ""),
    ("瀬戸美夜子", "濑户美夜子", "Seto Miyako", "已毕业"),
    ("御伽原江良", "御伽原江良", "Otogibara Era", "已毕业"),
    ("真堂雷斗", "真堂雷斗", "Shindo Raito", "已解约"),
    ("戌亥とこ", "戌亥床", "Inui Toko", ""),
    ("アンジュ・カトリーナ", "安洁·卡特莉娜", "Ange Katrina", ""),
    ("リゼ・ヘルエスタ", "莉泽·赫露艾斯塔", "Lize Helesta", ""),
    ("三枝明那", "三枝明那", "Saegusa Akina", ""),
    ("愛園愛美", "爱园爱美", "Aizono Manami", ""),
    ("鈴原るる", "铃原露露", "Suzuhara Lulu", ""),
    ("雪城眞尋", "雪城真寻", "Yukishiro Mahiro", ""),
    ("エクス・アルビオ", "艾克斯·阿尔比欧", "Ex Albio", ""),
    ("レヴィ・エリファ", "利维·艾莉法", "Levi Elipha", ""),
    ("葉山舞鈴", "叶山舞铃", "Hayama Marin", ""),
    ("ニュイ・ソシエール", "纽伊·索西艾瑞", "Nui Sociere", ""),
    ("加賀美ハヤト", "加贺美隼人", "Kagami Hayato", ""),
    ("葉加瀬冬雪", "叶加濑冬雪", "Hakase Fuyuki", ""),
    ("夜見れな", "夜见蕾娜", "Yorumi Rena", ""),
    ("アルス・アルマル", "阿露丝·阿尔玛", "Ars Almal", ""),
    ("相羽ういは", "相羽初叶", "Aiba Uiha", "已毕业"),
    ("黛灰", "黛灰", "Mayuzumi Kai", "已毕业"),
    ("エリー・コニファー", "艾莉·柯妮法", "Eli Conifer", ""),
    ("ラトナ・プティ", "拉特娜·葡蒂", "Ratna Petit", ""),
    ("天宮こころ", "天宫心", "Amamiya Kokoro", ""),
    ("早瀬走", "早濑走", "Hayase Sou", ""),
    ("健屋花那", "健屋花那", "Sukoya Kana", ""),
    ("シェリン・バーガンディ", "谢林·伯艮第", "Shellin Burgundy", ""),
    ("フミ", "文美", "Fumi", ""),
    ("星川サラ", "星川莎拉", "Hoshikawa Sara", ""),
    ("山神カルタ", "山神歌流多", "Yagami Karuta", ""),
    ("えま★おうがすと", "艾玛★奥加斯特", "Emma August", ""),
    ("ルイス・キャミー", "路易斯·嘉米", "Luis Cammy", ""),
    ("魔使マオ", "魔使真央", "Matsukai Mao", ""),
    ("不破湊", "不破凑", "Fuwa Minato", ""),
    ("白雪巴", "白雪巴", "Shirayuki Tomoe", ""),
    ("グウェル・オス・ガール", "圭利·奥什·迦尔", "Gwelu Os Gar", "已毕业"),
    ("ましろ爻", "真白爻", "Mashiro Meme", ""),
    ("奈羅花", "奈罗花", "Naraka", "已毕业"),
    ("来栖夏芽", "来栖夏芽", "Kurusu Natsume", ""),
    ("フレン・E・ルスタリオ", "芙莲·E·露丝塔莉欧", "Furen E Lustario", ""),
    ("メリッサ・キンレンカ", "梅丽莎·金莲花", "Melissa Kinrenka", "已毕业"),
    ("イブラヒム", "伊卜拉新", "Ibrahim", ""),
    ("長尾景", "长尾景", "Nagao Kei", ""),
    ("弦月藤士郎", "弦月藤士郎", "Genzuki Tojiro", ""),
    ("甲斐田晴", "甲斐田晴", "Kaida Haru", ""),
    ("金魚坂めいろ", "金鱼坂迷路", "Kingyozaka Meiro", "已解约"),
    ("空星きらめ", "空星煌", "Sorahoshi Kirame", ""),
    ("西園チグサ", "西园千草", "Nishizono Chigusa", ""),
    ("朝日南アカネ", "朝日南茜", "Asahina Akane", "已毕业"),
    ("周央サンゴ", "周央珊瑚", "Suo Sango", ""),
    ("東堂コハク", "东堂琥珀", "Todo Kohaku", ""),
    ("北小路ヒスイ", "北小路翡翠", "Kitakoji Hisui", ""),
    ("アクシア・クローネ", "艾西亚·克朗", "Axia Krone", "已毕业"),
    ("ローレン・イロアス", "劳伦·伊罗斯", "Lauren Iroas", ""),
    ("レオス・ヴィンセント", "雷奥斯·文森特", "Leos Vincent", ""),
    ("オリバー・エバンス", "奥利弗·埃文斯", "Oliver Evans", ""),
    ("レイン・パターソン", "兰·帕特森", "Lain Paterson", ""),
    ("海妹四葉", "海妹四叶", "Umise Yotsuha", ""),
    ("天ヶ瀬むゆ", "天瀬梦愈", "Amagase Muyu", ""),
    ("先斗寧", "先斗宁", "Ponto Nei", ""),
    ("壱百満天原サロメ", "壹百满天原莎乐美", "Hyakumantenbara Salome", ""),
    ("風楽奏斗", "风乐奏斗", "Fura Kanato", ""),
    ("渡会雲雀", "渡会云雀", "Watarai Hibari", ""),
    ("四季凪アキラ", "四季凪圣来", "Shikinagi Akira", ""),
    ("セラフ・ダズルガーデン", "塞拉弗·迪滋加登", "Seraph Dazzlegarden", ""),
    ("小清水透", "小清水透", "Koshimizu Toru", ""),
    ("獅子堂あかり", "狮子堂灯", "Shishido Akari", ""),
    ("鏑木ろこ", "镝木露恋", "Kaburaki Roco", ""),
    ("五十嵐梨花", "五十岚梨花", "Igarashi Rika", ""),
    ("石神のぞみ", "石神望", "Ishigami Nozomi", ""),
    ("ソフィア・ヴァレンタイン", "苏菲娅·瓦纶玎", "Sophia Valentine", ""),
    ("倉持めると", "仓持妹路特", "Kuramochi Meruto", ""),
    ("赤城ウェン", "赤城文", "Akagi Wen", ""),
    ("宇佐美リト", "宇佐美理人", "Usami Rito", ""),
    ("佐伯イッテツ", "佐伯一彻", "Saiki Ittetsu", ""),
    ("緋八マナ", "绯八舞成", "Hibachi Mana", ""),
    ("星導ショウ", "星导霄", "Hoshirube Sho", ""),
    ("叢雲カゲツ", "丛云花月", "Murakumo Kagetsu", ""),
    ("小柳ロウ", "小柳狼", "Koyanagi Rou", ""),
    ("伊波ライ", "伊波雷", "Inami Rai", ""),
    ("立伝都々", "立传都都", "Tachitsute Toto", ""),
    ("栞葉るり", "栞叶琉璃", "Shioriha Ruri", ""),
    ("ミラン・ケストレル", "米兰·凯斯特雷尔", "Milan Kestrel", ""),
    ("北見遊征", "北见游征", "Kitami Yusei", ""),
    ("魁星", "魁星", "Kaisei", ""),
    ("榊ネス", "榊奈司", "Sakaki Ness", ""),
    ("綺沙良", "绮沙良", "Kisara", ""),
    ("梢桃音", "梢桃音", "Kozue Mone", ""),
    ("ルンルン", "仑仑", "Lunlun", ""),
    ("司賀りこ", "司贺莉子", "Shiga Riko", ""),
    ("珠乃井ナナ", "珠乃井南奈", "Tamanoi Nana", ""),
    ("雲母たまこ", "云母玉子", "Kirara Tamako", ""),
    ("渚トラウト", "渚托劳特", "Nagisa Trout", ""),
    ("七瀬すず菜", "七濑铃菜", "Nanase Suzuna", ""),
    ("酒寄颯馬", "酒寄飒马", "Sakayori Soma", ""),
    ("早乙女ベリー", "早乙女蓓丽", "Saotome Berry", ""),
    ("五木左京", "五木左京", "Itsuki Sakyo", ""),
    ("一橋綾人", "一桥绫人", "Hitotsubashi Ayato", ""),
]

ORG_TERMS = [
    (
        "にじさんじ",
        "彩虹社",
        "NIJISANJI",
        "日本VTuber事务所；中文圈常称「彩虹社」。",
        "にじさんじ所属の配信。",
        "可写作 NIJISANJI / Nijisanji。",
    ),
    (
        "彩虹社",
        "彩虹社",
        "NIJISANJI",
        "にじさんじ的中文常用称呼。",
        "彩虹社所属liver。",
        "",
    ),
]


def build_entry(jp: str, zh: str, romaji: str, note: str) -> dict:
    aliases = [zh, romaji]
    if zh != jp:
        aliases.append(jp)
    # 简体/繁体常见混用
    trad_map = {"叶": "葉", "枫": "楓", "见": "見", "乐": "樂", "涩": "渋"}
    for s, t in trad_map.items():
        if s in zh and t not in aliases:
            aliases.append(zh.replace(s, t))
    notes = f"中文圈固定译名「{zh}」，指彩虹社（NIJISANJI）成员。"
    if note:
        notes += f"（{note}）"
    return {
        "term": jp,
        "aliases": list(dict.fromkeys(a for a in aliases if a)),
        "category": "nijisanji",
        "translation": zh,
        "meaning": f"彩虹社所属VTuber {zh}（{romaji}）。",
        "examples": [f"{jp}の配信", f"{zh}さん"],
        "notes": notes,
    }


def main():
    terms = [build_entry(jp, zh, romaji, note) for jp, zh, romaji, note in MEMBERS]
    for jp, zh, romaji, meaning, example, notes in ORG_TERMS:
        terms.insert(
            0,
            {
                "term": jp,
                "aliases": [zh, romaji, "Nijisanji", "彩虹社"],
                "category": "nijisanji",
                "translation": zh,
                "meaning": meaning,
                "examples": [example],
                "notes": notes or f"组织名，中文常用「{zh}」。",
            },
        )
    out = Path(__file__).resolve().parents[1] / "backend" / "app" / "data" / "terms" / "vtuber.json"
    out.write_text(json.dumps(terms, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(terms)} entries to {out}")


if __name__ == "__main__":
    main()
